### PR TITLE
Rename GameTick to GameFrame

### PR DESCRIPTION
**Pull request by dlsteuer**
Handles battlesnakeio/roadmap#64

### CODE REVIEW

**Comment by graeme-hill** [comment]
Awesome I agree that `GameFrame` is a better name :+1: However it might make it more confusing if we don't change it everywhere. For example it looks like this PR leaves the word "tick" in a lot of places where really "frame" makes more sense now. Examples:

Before it was ticks everywhere but now a mixture of ticks/frames in `ListGameFrames`:

```
return &pb.ListGameFramesResponse{
	Ticks: ticks,
	Count: int32(len(ticks)),
}, nil
```

The `Store` interface now has a function signature like this:

```
PushGameTick(c context.Context, id string, t *pb.GameFrame) error
```

etc..

I would just go all out and change them all to frame. In fact from my ctrl+f'ing it looks like pretty much every instance of tick should be frame outside the vendor folder of course.... and nothing can ever go wrong with a project wide replace-all...

**Comment by graeme-hill** [comment]
Looks like you got some of those just before I posted my comment... so the examples may be out of date.

**Comment by dlsteuer** [comment]
Yup still working through them all 😀

**Comment by dlsteuer** [comment]
@graeme-hill i think i got them all now. I left one thing as GameTick, this is the actual GameTick function, which is the process from where the previous frame is processed into the next frame.

**Comment by graeme-hill** [comment]
Looks good now. That must have been tedious.

**Pull request merged**
