### PR TITLE
Official Snake

### PR DESCRIPTION
**Pull request by ColDog**
Add a snake url via an environment variable which will add `official=true` to prometheus metrics. This can allow us to make sure that the engine performance is rock solid for the day of by tracking it against a specific snake.

### CODE REVIEW

**Comment by dlsteuer** [comment]
What is the official snake?

**Comment by ColDog** [comment]
@dlsteuer answered in the description

> Add a snake url via an environment variable which will add `official=true` to prometheus metrics. This can allow us to make sure that the engine performance is rock solid for the day of by tracking it against a specific snake.

**Comment by dlsteuer** [comment]
This kinda of makes sense, but I don't see how this measures engine performance, it seems to be measuring the time to make a call to a single snake. This snake would need to be playing in games constantly to get the measurement into prometheus.

**Comment by ColDog** [comment]
@dlsteuer ya that's the goal it's also to measure error rate out of the engine. Are we getting timeouts? How many calls are we missing? This snake we can actually alert on timeouts out of the engine because we know that the snake should be working.

**Pull request merged**
