### PR TITLE
pass in timeout at game creation

### PR DESCRIPTION
**Pull request by codeallthethingz**
Now defaults to 500.  < 1 and > 5000 get ignored and default to 500

### CODE REVIEW

**Comment by codeallthethingz** [comment]
fixes roadmap/issues#163

**Comment by codeallthethingz** [comment]
@dlsteuer might need some help with this. :(

**Comment by dlsteuer** [comment]
Ah yeah, I've seen this before it went away on a re-run

**Comment by dlsteuer** [comment]
@codeallthethingz I re-ran the tests on travis, and they passed, let's move the data race issue into a roadmap issue, and we can push this ticket out.

**Comment by codeallthethingz** [comment]
I tried that three times!  :)

**Comment by codeallthethingz** [comment]
opened bug for race condition https://github.com/battlesnakeio/roadmap/issues/238

**Pull request merged**
